version: '3.4'

services:
  royce:
    container_name: royce
    image: royce
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb/mongodb
    depends_on:
      - mongodb
    networks:
      - my-network
    
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: ["--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    restart: always
    networks:
      - my-network


volumes:
  data:

networks:
  my-network:
    driver: bridge
