version: '3.4'

services:
  royce:
    container_name: royce
    image: royce
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongodb/mongodb
    depends_on:
      - mongodb
    networks:
      mongo_net:
    
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    restart: always
    networks:
      mongo_net:
        ipv4_address: 172.16.0.1
    command: mongod --bind_ip 127.0.0.1,172.16.0.1


volumes:
  data:

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.254
